Repository globaldothealth/list, pull requests merged in 2020-04, with the labels that each got.

#1 Create skeletal Node apps for the curator and data services.
  data-serving/data-service/.gitignore
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  data-serving/data-service/src/index.ts
  data-serving/data-service/tsconfig.json
  data-serving/data-service/tslint.json
  verification/curator-service/.gitignore
  verification/curator-service/package-lock.json
  verification/curator-service/package.json
  verification/curator-service/src/index.ts
  verification/curator-service/tsconfig.json
  verification/curator-service/tslint.json
Labels: enhancement

#3 Setting up a base GitHub action for our Node apps.
  .github/workflows/nodejs.yml
  data-serving/data-service/package.json
  verification/curator-service/package.json
Labels: enhancement

#4 Create serving structure and add skeletal read case data methods to the data service.
  data-serving/data-service/jest.config.js
  data-serving/data-service/nodemon.json
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/controllers/home.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/src/server.ts
  data-serving/data-service/test/case.test.ts
  data-serving/data-service/test/home.test.ts
  data-serving/data-service/test/index.test.ts
Labels: enhancement

#9 Adding description and repository data to data-service package.json.
  data-serving/data-service/package.json
Labels: documentation

#10 Bring curator-service up to speed with baseline structure/utilities
  .github/workflows/nodejs.yml
  verification/curator-service/.eslintignore
  verification/curator-service/.eslintrc.js
  verification/curator-service/.prettierrc.js
  verification/curator-service/jest.config.js
  verification/curator-service/nodemon.json
  verification/curator-service/package-lock.json
  verification/curator-service/package.json
  verification/curator-service/src/controllers/home.ts
  verification/curator-service/src/index.ts
  verification/curator-service/src/server.ts
  verification/curator-service/test/home.test.ts
  verification/curator-service/test/index.test.ts
Labels: enhancement

#14 Adding recommended VSCode settings file for auto-linting/formatting.
  dev/.vscode/settings.json
Labels: documentation

#12 Base create method for case data
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/controllers/home.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/test/case.test.ts
Labels: enhancement

#16 Adding base update/delete methods to case data API.
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/test/case.test.ts
Labels: enhancement

#17 dotenv set up for both services
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  data-serving/data-service/src/index.ts
  verification/curator-service/package-lock.json
  verification/curator-service/package.json
  verification/curator-service/src/index.ts
Labels: enhancement

#18 Fix eslint baseline config </shamecube>.
  data-serving/data-service/.eslintrc.js
Labels: bug

#19 Correcting curator-service linter ref, too, and applying a handful of…
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/controllers/home.ts
  verification/curator-service/.eslintrc.js
  verification/curator-service/src/controllers/home.ts
  verification/curator-service/src/controllers/sources.ts
  verification/curator-service/src/index.ts
Labels: bug

#20 Update README.md to contain latest CI status
  README.md
Labels: documentation

#22 Validate env with envalid
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  data-serving/data-service/src/index.ts
  data-serving/data-service/src/server.ts
  data-serving/data-service/src/util/validate-env.ts
Labels: enhancement

#25 Connect curator service to mongodb using mongoose
  verification/curator-service/jest-mongodb-config.js
  verification/curator-service/jest.config.js
  verification/curator-service/package-lock.json
  verification/curator-service/package.json
  verification/curator-service/src/controllers/sources.ts
  verification/curator-service/src/index.ts
  verification/curator-service/src/model/source.ts
  verification/curator-service/test/sources.test.ts
Labels: enhancement

#24 Implement an object-managed connection to MongoDB in data-service; use it in case API; facilitate testing
  data-serving/data-service/jest-mongodb-config.js
  data-serving/data-service/jest.config.js
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  data-serving/data-service/src/common/db-client.ts
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/src/model/case.ts
  data-serving/data-service/src/util/validate-env.ts
  data-serving/data-service/test/case.test.ts
Labels: enhancement

#28 Updating function comments in case API controller to reflect new paths.
  data-serving/data-service/src/controllers/case.ts
Labels: documentation

#27 Wire the remainder of the data-service case API to DB
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/test/case.test.ts
Labels: enhancement

#30 Update mongoose options, case API validation mechanism, and corresponding testing
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/test/case.test.ts
Labels: enhancement

#29 Implement CRUD api for sources
  verification/curator-service/src/controllers/sources.ts
  verification/curator-service/src/index.ts
  verification/curator-service/test/sources.test.ts
Labels: enhancement

#31 Render summary from data-service API on the curator-service home page.
  verification/curator-service/package-lock.json
  verification/curator-service/package.json
  verification/curator-service/src/controllers/home.ts
  verification/curator-service/src/index.ts
  verification/curator-service/test/home.test.ts
Labels: enhancement

#34 Add npm scripts for jest watch mode(s).
  data-serving/data-service/package.json
Labels: enhancement

#36 Curator service dotenv
  verification/curator-service/package-lock.json
  verification/curator-service/package.json
  verification/curator-service/src/index.ts
  verification/curator-service/src/util/validate-env.ts
Labels: enhancement

#38 Move curator backend code to a dedicated dir, in preparation for creating a separate /ui/ dir.
  .github/workflows/nodejs.yml
  dev/docker-compose.dev.yml
  dev/docker-compose.yml
  verification/curator-service/api/.dockerignore
  verification/curator-service/api/.eslintignore
  verification/curator-service/api/.eslintrc.js
  verification/curator-service/api/.gitignore
  verification/curator-service/api/.prettierrc.js
  verification/curator-service/api/Dockerfile
  verification/curator-service/api/jest-mongodb-config.js
  verification/curator-service/api/jest.config.js
  verification/curator-service/api/nodemon.json
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/home.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/src/server.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/home.test.ts
  verification/curator-service/api/test/index.test.ts
  verification/curator-service/api/test/sources.test.ts
  verification/curator-service/api/tsconfig.json
  verification/curator-service/api/tslint.json
Labels: enhancement

#40 Add init container to docker-compose images
  dev/docker-compose.dev.yml
  dev/docker-compose.yml
Labels: enhancement

#39 Completed schemas for sources
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/src/schemas/README.md
  verification/curator-service/api/src/schemas/configs.schema.json
Labels: enhancement

#43 Setting up an initial curator-service/ui React app with CRA.
  verification/curator-service/ui/.gitignore
  verification/curator-service/ui/README.md
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/public/favicon.ico
  verification/curator-service/ui/public/index.html
  verification/curator-service/ui/public/logo192.png
  verification/curator-service/ui/public/logo512.png
  verification/curator-service/ui/public/manifest.json
  verification/curator-service/ui/public/robots.txt
  verification/curator-service/ui/src/App.css
  verification/curator-service/ui/src/App.test.tsx
  verification/curator-service/ui/src/App.tsx
  verification/curator-service/ui/src/index.css
  verification/curator-service/ui/src/index.tsx
  verification/curator-service/ui/src/logo.svg
  verification/curator-service/ui/src/react-app-env.d.ts
  verification/curator-service/ui/src/serviceWorker.ts
  verification/curator-service/ui/src/setupTests.ts
  verification/curator-service/ui/tsconfig.json
Labels: enhancement

#46 reenabled curl fetches of docker stack in github workflow
  .github/workflows/docker.yml
Labels: enhancement

#47 added pagination support to /api/sources
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#45 Initial React frontend that queries curator-service API (proxy) and display line list data
  verification/curator-service/api/src/controllers/cases.ts
  verification/curator-service/api/src/controllers/home.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/cases.test.ts
  verification/curator-service/api/test/home.test.ts
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/App.css
  verification/curator-service/ui/src/App.test.tsx
  verification/curator-service/ui/src/App.tsx
  verification/curator-service/ui/src/components/App.test.tsx
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.test.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
  verification/curator-service/ui/src/components/LinelistCaseRow.test.tsx
  verification/curator-service/ui/src/components/LinelistCaseRow.tsx
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
  verification/curator-service/ui/src/index.tsx
Labels: enhancement

#50 Small tweak to displaying dates, and wrapping this in a util function.
  verification/curator-service/ui/src/components/LinelistCaseRow.test.tsx
  verification/curator-service/ui/src/components/LinelistCaseRow.tsx
  verification/curator-service/ui/src/util/display-date.ts
Labels: enhancement

#52 Paginate the case data table (and a couple other things)
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
  verification/curator-service/ui/src/components/LinelistCaseRow.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
  verification/curator-service/ui/src/index.tsx
Labels: enhancement

#58 add basic form to submit new case
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/NewCaseForm.test.tsx
  verification/curator-service/ui/src/components/NewCaseForm.tsx
Labels: enhancement

#59 tweak topbar
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.test.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
Labels: enhancement

#62 Submit form to create new cases
  verification/curator-service/ui/src/components/NewCaseForm.test.tsx
  verification/curator-service/ui/src/components/NewCaseForm.tsx
Labels: enhancement
