Repository globaldothealth/list, pull requests merged in 2020-06, with the labels that each got.

#209 Integrate the Source API update method with AWS CloudWatch Events
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#210 Converter: Handle lists of locations in the travelHistory field
  data-serving/scripts/convert-data/converters.py
  data-serving/scripts/convert-data/parsers.py
Labels: enhancement

#211 Add deletion to the AWS CWE client API; integrate this with the Sources API
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/test/clients/aws-events-clients.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#213 Add logic that dictates whether AWS CW rules are put or deleted during source updates
  verification/curator-service/api/src/controllers/sources.ts
Labels: enhancement

#215 Expose curator services externally
  aws/README.md
  aws/alb-ingress-controller.yaml
  aws/alb-ingress-iam-policy.json
  aws/curator-ingress.yaml
  aws/curator.yaml
  aws/data.yaml
  aws/rbac-role.yaml
Labels: enhancement

#218 Add health checks based on mongoose connection state
  aws/curator.yaml
  aws/data.yaml
  data-serving/data-service/src/index.ts
  data-serving/data-service/test/index.test.ts
  dev/docker-compose.yml
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/index.test.ts
Labels: enhancement

#217 Populate rule description in our AWS CW events client library
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/clients/aws-events-client.test.ts
  verification/curator-service/api/test/model/source.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#224 Populate source rule targets to trigger the global retrieval function
  verification/curator-service/api/package.json
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/clients/aws-events-client.test.ts
Labels: enhancement

#228 Wire up the source API to set rule targets to the global retrieval Lambda ARN
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/clients/aws-events-client.test.ts
  verification/curator-service/api/test/model/source.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#230 copy openapi folder in prod curator image
  verification/curator-service/Dockerfile
Labels: bug

#227 Consolidate getting started instructions into dev/README.md
  dev/README.md
Labels: documentation

#231 s/aws-alb/kubernetes-nginx and s/fargate/managedNodeGroups
  README.md
  aws/README.md
  aws/alb-ingress-controller.yaml
  aws/alb-ingress-iam-policy.json
  aws/cluster.yaml
  aws/curator-ingress.yaml
  aws/curator.yaml
  aws/data.yaml
  aws/letsencrypt.yaml
  aws/rbac-role.yaml
Labels: enhancement

#234 Add an HTTP bearer token auth strategy for the curator server
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/src/model/user.ts
  verification/curator-service/api/test/auth.test.ts
  verification/curator-service/api/test/model/user.test.ts
Labels: enhancement

#241 use same site cookie strict for session cookie
  verification/curator-service/api/src/index.ts
Labels: enhancement

#243 Fix cron schedule to be at 5am precisely, not... every minute during the 5am hour
  .github/workflows/case-data-update.yml
Labels: bug

#240 Add full, authenticated retrieval using the Source API (for JSON content)
  .gitignore
  ingestion/functions/ci-requirements.txt
  ingestion/functions/retrieval/requirements.txt
  ingestion/functions/retrieval/retrieval.py
  ingestion/functions/retrieval/retrieval_test.py
  ingestion/functions/retrieval/valid_scheduled_event.json
  ingestion/functions/template.yaml
Labels: enhancement

#245 Initial parser for COVID19-India API data
  ingestion/functions/parsing/india/__init__.py
  ingestion/functions/parsing/india/india.py
  ingestion/functions/parsing/india/india_test.py
  ingestion/functions/parsing/india/input_event.json
  ingestion/functions/parsing/india/requirements.txt
  ingestion/functions/parsing/india/sample_data.json
Labels: enhancement

#252 Add India parser function SAM definition; trigger source parser lambdas in retrieval
  ingestion/functions/retrieval/retrieval.py
  ingestion/functions/retrieval/retrieval_test.py
  ingestion/functions/template.yaml
Labels: enhancement

#253 Add parser Lambda ARN to the SourceTable
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#255 Set trust proxy to allow the use of secure session cookies behind nginx.
  verification/curator-service/api/src/index.ts
Labels: bug

#262 Add geo admin areas to linelist table
  verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: enhancement

#265 Basic AWS Lambda client to add resource-scoped permissions to Lambda functions
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/clients/aws-lambda-client.ts
  verification/curator-service/api/src/util/assert-string.ts
  verification/curator-service/api/test/clients/aws-lambda-client.test.ts
Labels: enhancement

#266 Create resource-specific Lambda permission in the Source API
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/clients/aws-lambda-client.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/clients/aws-events-client.test.ts
  verification/curator-service/api/test/clients/aws-lambda-client.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#270 Configure resource-based policy for Lambdas in update operations
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/clients/aws-events-client.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#271 Remove resourced-based policy permissions in source API delete operations
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/src/clients/aws-lambda-client.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/clients/aws-events-client.test.ts
  verification/curator-service/api/test/clients/aws-lambda-client.test.ts
  verification/curator-service/api/test/model/source.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#268 Add mapbox geocoding capability
  dev/docker-compose.ci.yml
  dev/docker-compose.yml
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/cases.ts
  verification/curator-service/api/src/geocoding/README.md
  verification/curator-service/api/src/geocoding/fake.ts
  verification/curator-service/api/src/geocoding/geocoder.ts
  verification/curator-service/api/src/geocoding/mapbox.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/auth.test.ts
  verification/curator-service/api/test/cases.test.ts
  verification/curator-service/api/test/geocoding/fake.test.ts
  verification/curator-service/api/test/geocoding/lyon.json
  verification/curator-service/api/test/geocoding/mapbox.test.ts
  verification/curator-service/api/test/index.test.ts
  verification/curator-service/api/test/sources.test.ts
  verification/curator-service/api/test/users.test.ts
Labels: enhancement

#288 pass mapbox token to curator services on aws
  aws/curator.yaml
Labels: enhancement

#287 Geocode new cases
  data-serving/scripts/setup-db/README.md
  verification/curator-service/api/src/controllers/cases.ts
  verification/curator-service/api/src/geocoding/fake.ts
  verification/curator-service/api/src/geocoding/geocoder.ts
  verification/curator-service/api/src/geocoding/mapbox.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/auth.test.ts
  verification/curator-service/api/test/cases.test.ts
  verification/curator-service/api/test/geocoding/mapbox.test.ts
  verification/curator-service/api/test/index.test.ts
  verification/curator-service/api/test/sources.test.ts
  verification/curator-service/api/test/users.test.ts
  verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
  verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
  verification/curator-service/ui/cypress/support/commands.ts
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
  verification/curator-service/ui/src/components/NewCaseForm.test.tsx
  verification/curator-service/ui/src/components/NewCaseForm.tsx
Labels: enhancement

#280 Ingestion functions readme
  ingestion/functions/README.md
  ingestion/functions/assets/system.svg
Labels: documentation

#291 Fix example command in ingestion documentation
  ingestion/functions/README.md
Labels: bug, documentation

#301 Add a proxy upsert API to the curator service
  verification/curator-service/api/src/controllers/cases.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/cases.test.ts
Labels: enhancement

#299 Add CaseReference object, per spec, to our case schema/model
  data-serving/data-service/schemas/cases.schema.json
  data-serving/data-service/src/model/case-reference.ts
  data-serving/data-service/src/model/case.ts
  data-serving/data-service/test/model/case-reference.test.ts
  data-serving/data-service/test/model/data/case-reference.full.json
  data-serving/data-service/test/model/data/case-reference.minimal.json
  data-serving/data-service/test/model/data/case.full.json
Labels: enhancement

#300 Add the case upsert API to the data service
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/test/controllers/case.test.ts
  verification/curator-service/api/src/controllers/cases.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/cases.test.ts
Labels: enhancement

#315 Fix example case.json
  data-serving/data-service/schemas/cases.schema.json
  data-serving/samples/cases.json
Labels: bug

#319 Update retrieval/India parsing functions: (1) based on case schema changes; (2) to use the upsert API
  ingestion/functions/parsing/india/india.py
  ingestion/functions/parsing/india/india_test.py
  ingestion/functions/parsing/india/input_event.json
  ingestion/functions/retrieval/retrieval.py
  ingestion/functions/retrieval/retrieval_test.py
  ingestion/functions/template.yaml
Labels: enhancement

#331 Maybe try to fix daily case update workflow?
  .github/workflows/case-data-update.yml
  data-serving/scripts/setup-db/package.json
Labels: bug

#341 Fix incorrect path in README
  dev/README.md
Labels: documentation

#336 Basic bulk case entry page
  verification/curator-service/ui/cypress/fixtures/bad_bulk_data.csv
  verification/curator-service/ui/cypress/fixtures/bulk_data.csv
  verification/curator-service/ui/cypress/fixtures/example.json
  verification/curator-service/ui/cypress/fixtures/updated_bulk_data.csv
  verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
  verification/curator-service/ui/cypress/support/commands.ts
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/BulkCaseForm.test.tsx
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
Labels: enhancement

#343 Update API spec for case upsert (and update codes)
  data-serving/data-service/api/openapi.yaml
  verification/curator-service/api/openapi/openapi.yaml
Labels: documentation

#344 Add a precommit hook to invoke our eslint linting/formatting config
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/users.ts
  verification/curator-service/ui/.eslintrc.js
  verification/curator-service/ui/cypress/support/commands.ts
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
  verification/curator-service/ui/src/components/Users.test.tsx
Labels: enhancement

#362 Set up form for bulk upload interface; separate file upload from submission
  verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
  verification/curator-service/ui/src/components/BulkCaseForm.test.tsx
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
Labels: enhancement

#363 Bulk formik upload component
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
  verification/curator-service/ui/src/components/NewCaseForm.tsx
  verification/curator-service/ui/src/components/bulk-case-form-fields/FileUpload.tsx
  verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx
  verification/curator-service/ui/src/components/common-form-fields/Source.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/GenomeSequences.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
Labels: enhancement

#369 documentation for curator service/ui
  verification/curator-service/api/README.md
  verification/curator-service/api/src/geocoding/README.md
  verification/curator-service/auth.md
  verification/curator-service/ui/README.md
Labels: documentation
