Repository globaldothealth/list, pull requests merged in 2020-05, with the labels that each got.

#69 add total count to pagination of curator service sources api
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#68 Paginate /api/cases results
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/src/index.ts
  data-serving/data-service/test/case.test.ts
  data-serving/data-service/test/model/case.test.ts
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: enhancement

#67 fix frontend to be able to submit cases as per new schema
  data-serving/data-service/src/model/case.ts
  verification/curator-service/ui/src/components/NewCaseForm.test.tsx
  verification/curator-service/ui/src/components/NewCaseForm.tsx
Labels: enhancement

#74 Use material-table in list view
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/public/index.html
  verification/curator-service/ui/src/components/LinelistCaseRow.test.tsx
  verification/curator-service/ui/src/components/LinelistCaseRow.tsx
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: enhancement

#78 support filtering of notes with regexp
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/test/case.test.ts
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: enhancement

#76 Create a bare-bones SAM/CF structure and retrieval Lambda function
  .gitignore
  ingestion/functions/.gitignore
  ingestion/functions/README.md
  ingestion/functions/retrieval/__init__.py
  ingestion/functions/retrieval/requirements.txt
  ingestion/functions/retrieval/retrieval.py
  ingestion/functions/retrieval/retrieval_test.py
  ingestion/functions/retrieval/scheduled_event.json
  ingestion/functions/template.yaml
Labels: enhancement

#83 Convert the outbreakSpecifics field
  data-serving/scripts/README.md
  data-serving/scripts/convert_data.py
  data-serving/scripts/converters.py
Labels: enhancement

#85 Adding SAM config file (standardizes serverless resource deployment p…
  ingestion/functions/samconfig.toml
Labels: enhancement

#81 Exclude node_modules in sample vscode settings.json.
  dev/.vscode/settings.json
Labels: documentation

#89 Flatten Case data to display it in the table
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: enhancement

#88 Add S3 integration to the retrieval Lambda
  ingestion/functions/pytest.ini
  ingestion/functions/retrieval/invalid_scheduled_event.json
  ingestion/functions/retrieval/retrieval.py
  ingestion/functions/retrieval/retrieval_test.py
  ingestion/functions/retrieval/valid_scheduled_event.json
Labels: enhancement

#87 Update README for converter with details on status of conversion
  data-serving/scripts/README.md
Labels: documentation

#91 stop testing on node 10.x we're not using it
  .github/workflows/curator-api-node.yml
  .github/workflows/curator-ui-node.yml
  .github/workflows/data-service-node.yml
Labels: enhancement

#86 Convert the travel history column
  data-serving/scripts/README.md
  data-serving/scripts/constants.py
  data-serving/scripts/convert_data.py
  data-serving/scripts/converters.py
Labels: enhancement

#92 Grant retrieval lambda write access to S3.
  ingestion/functions/retrieval/retrieval.py
  ingestion/functions/template.yaml
Labels: bug

#93 Barebones Python CI action for ingestion functions.
  .github/workflows/ingestion-functions-python.yml
  ingestion/functions/ci-requirements.txt
  ingestion/functions/pytest.ini
Labels: enhancement

#95 Add auth model and no-op passport integration
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/model/user.ts
  verification/curator-service/api/test/model/source.test.ts
  verification/curator-service/api/test/model/user.test.ts
Labels: enhancement

#96 Change routes in frontend so that / can be a simple explanation page and not require auth
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.test.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
Labels: enhancement

#97 Support authentication via google oauth 2.0
  verification/curator-service/api/env
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/model/user.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/auth.test.ts
Labels: enhancement

#98 I was wrong: mongodb needs the Z(ulu) at the end of time strings
  data-serving/scripts/converters.py
  data-serving/scripts/utils.py
Labels: bug

#104 Basic GitHub action deploying SAM stack.
  .github/workflows/ingestion-aws-sam-deploy.yml
Labels: enhancement

#103 Basic GitHub action verifying SAM build.
  .github/workflows/ingestion-aws-sam-build.yml
Labels: enhancement

#102 proxy requests from 3002 to 3001 so that the UI only talks to itself
  dev/docker-compose.yml
  verification/curator-service/ui/Dockerfile
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/LinelistTable.tsx
  verification/curator-service/ui/src/components/NewCaseForm.tsx
  verification/curator-service/ui/src/setupProxy.js
Labels: enhancement

#105 make ID column not editable
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: enhancement

#106 Proxy /api/cases calls manually in curator frontend
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/cases.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/cases.test.ts
Labels: enhancement

#108 Add an /auth/profile API handler to prepare for showing login/logout buttons in the UI navbar
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/test/auth.test.ts
  verification/curator-service/ui/src/components/EpidNavbar.tsx
Labels: enhancement

#112 Add SAM build/deploy status badge to home README
  README.md
Labels: documentation

#117 add login/logout buttons to navbar
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.test.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
  verification/curator-service/ui/src/index.tsx
  verification/curator-service/ui/src/setupProxy.js
Labels: enhancement

#119 Store session info in Mongo
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/test/auth.test.ts
  verification/curator-service/api/test/cases.test.ts
  verification/curator-service/api/test/home.test.ts
  verification/curator-service/api/test/index.test.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#121 Setup login redirects to work in dev
  dev/docker-compose.yml
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/ui/Dockerfile
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/EpidNavbar.tsx
Labels: enhancement

#111 Raise docker-compose build context dir to allow file sharing
  data-serving/data-service/Dockerfile
  dev/docker-compose.yml
  verification/curator-service/api/Dockerfile
  verification/curator-service/ui/Dockerfile
Labels: enhancement

#116 Initial script to setup db: create collection, apply validator, and drop data
  data-serving/scripts/import-data/package-lock.json
  data-serving/scripts/import-data/package.json
  data-serving/scripts/import-data/src/index.ts
  data-serving/scripts/import-data/src/types/mongo-cli.d.ts
Labels: enhancement

#109 Create/use a base tsconfig file.
  common/tsconfig.json
  data-serving/data-service/Dockerfile
  data-serving/data-service/tsconfig.json
  data-serving/scripts/import-data/tsconfig.json
  verification/curator-service/api/Dockerfile
  verification/curator-service/api/tsconfig.json
  verification/curator-service/ui/Dockerfile
  verification/curator-service/ui/tsconfig.json
Labels: enhancement

#126 Remove tslint files (we've been using eslint typescript integration, …
  data-serving/data-service/tslint.json
  data-serving/scripts/import-data/tslint.json
  verification/curator-service/api/tslint.json
Labels: enhancement

#128 Add a dev script to set up the local cases db and populate it with sample data
  data-serving/scripts/setup-db/tsconfig.json
  dev/README.md
  dev/setup_db.sh
Labels: enhancement

#134 Fix null reference bug with source validator
  data-serving/data-service/src/model/source.ts
  data-serving/data-service/test/model/source.test.ts
Labels: bug

#136 Fix format of events sent over the wire
  verification/curator-service/ui/src/components/LinelistTable.tsx
Labels: bug

#137 Update schema to work with documents created by dataserver
  data-serving/data-service/schemas/cases.schema.json
Labels: bug

#139 add docker config to serve UI from curator express server
  .github/workflows/docker.yml
  dev/docker-compose.dev.yml
  dev/docker-compose.yml
  prod/README.md
  prod/docker-compose.ci.yml
  prod/docker-compose.yml
  prod/run_stack.sh
  verification/curator-service/Dockerfile
  verification/curator-service/api/Dockerfile
  verification/curator-service/api/src/controllers/home.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/home.test.ts
  verification/curator-service/ui/Dockerfile
  verification/curator-service/ui/src/setupProxy.js
Labels: enhancement

#141 Barebones /sources curator UI page
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#144 basic setup for ecs fargate cluster running data service only
  aws/README.md
  aws/docker-compose.yml
  aws/ecs-params.yml
  prod/README.md
  prod/docker-compose.ci.yml
  prod/docker-compose.yml
  prod/run_stack.sh
Labels: enhancement

#146 Make sources table editable; add deletion.
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#148 Update Source model based on current design
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/model/data/source.full.json
  verification/curator-service/api/test/model/data/source.minimal.json
  verification/curator-service/api/test/model/source.test.ts
Labels: enhancement

#152 Update SourceTable to align with ~current data model.
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#155 Return the created source from the Source API.
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/test/controllers/case.test.ts
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#157 Extract the origin sub-type from the top-level Source model
  verification/curator-service/api/src/model/origin.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/model/data/origin.full.json
  verification/curator-service/api/test/model/data/origin.minimal.json
  verification/curator-service/api/test/model/origin.test.ts
Labels: enhancement

#156 Enable creating rows in the SourceTable component.
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#161 Add row updates to the SourceTable component
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#162 Configure our React code to use the ~same eslint/prettier config as other dirs
  verification/curator-service/ui/.eslintignore
  verification/curator-service/ui/.eslintrc.js
  verification/curator-service/ui/.prettierrc.js
  verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
  verification/curator-service/ui/cypress/plugins/index.js
  verification/curator-service/ui/cypress/support/index.js
  verification/curator-service/ui/package-lock.json
  verification/curator-service/ui/package.json
  verification/curator-service/ui/src/components/App.test.tsx
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.test.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
  verification/curator-service/ui/src/components/LinelistTable.test.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
  verification/curator-service/ui/src/index.tsx
  verification/curator-service/ui/src/serviceWorker.ts
  verification/curator-service/ui/src/util/display-date.ts
Labels: enhancement

#164 Resolve curator-ui linter warnings (now that we have uniform linting in place)
  verification/curator-service/ui/src/components/App.tsx
  verification/curator-service/ui/src/components/EpidNavbar.tsx
  verification/curator-service/ui/src/components/LinelistTable.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
  verification/curator-service/ui/src/serviceWorker.ts
Labels: enhancement

#165 Display API errors on the sources page
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement

#174 exit process when DB can't connect
  data-serving/data-service/src/index.ts
  verification/curator-service/api/src/index.ts
Labels: enhancement

#176 gitignore cypress videos
  .gitignore
Labels: enhancement

#173 Prep Source schema for AWS API integration
  verification/curator-service/api/src/model/automation.ts
  verification/curator-service/api/src/model/parser.ts
  verification/curator-service/api/src/model/regex-parsing.ts
  verification/curator-service/api/src/model/schedule.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/test/model/automation.test.ts
  verification/curator-service/api/test/model/data/automation.full.json
  verification/curator-service/api/test/model/data/parser.full.json
  verification/curator-service/api/test/model/data/regex-parsing.full.json
  verification/curator-service/api/test/model/data/schedule.full.json
  verification/curator-service/api/test/model/data/source.full.json
  verification/curator-service/api/test/model/parser.test.ts
  verification/curator-service/api/test/model/regex-parsing.ts
  verification/curator-service/api/test/model/schedule.test.ts
Labels: enhancement

#184 example test using local auth
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/auth.test.ts
Labels: enhancement

#188 add roles checking middleware
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/test/auth.test.ts
Labels: enhancement

#183 Production tuning of docker images
  data-serving/data-service/Dockerfile
  dev/docker-compose.dev.yml
  dev/docker-compose.yml
  verification/curator-service/Dockerfile
  verification/curator-service/api/Dockerfile
  verification/curator-service/ui/Dockerfile
  verification/curator-service/ui/cypress/plugins/index.ts
Labels: enhancement

#182 Add a basic AWS CloudWatch Events client
  verification/curator-service/api/package-lock.json
  verification/curator-service/api/package.json
  verification/curator-service/api/src/clients/aws-events-client.ts
  verification/curator-service/api/test/clients/aws-events-clients.test.ts
Labels: enhancement

#189 Remove swagger package and update dependencies.
  data-serving/data-service/package-lock.json
  data-serving/data-service/package.json
Labels: bug

#190 Create AWS event rules from the Sources.create API
  verification/curator-service/api/package.json
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/model/automation.ts
  verification/curator-service/api/src/model/source.ts
  verification/curator-service/api/src/util/validate-env.ts
  verification/curator-service/api/test/model/automation.test.ts
  verification/curator-service/api/test/model/data/automation.minimal.json
  verification/curator-service/api/test/sources.test.ts
Labels: enhancement

#195 Add a validated schedule expression to the Source schedule model
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/src/model/schedule.ts
  verification/curator-service/api/test/model/data/automation.full.json
  verification/curator-service/api/test/model/data/automation.minimal.json
  verification/curator-service/api/test/model/data/schedule.full.json
  verification/curator-service/api/test/model/data/source.full.json
  verification/curator-service/api/test/model/schedule.test.ts
Labels: enhancement

#200 close DB after clearDB task run
  verification/curator-service/ui/cypress/plugins/index.ts
Labels: bug

#198 Make source.automation.schedule.awsRuleArn optional
  verification/curator-service/api/src/model/schedule.ts
  verification/curator-service/api/test/model/data/schedule.minimal.json
  verification/curator-service/api/test/model/schedule.test.ts
Labels: enhancement

#199 Enable authorization
  .gitignore
  verification/curator-service/api/src/controllers/auth.ts
  verification/curator-service/api/src/controllers/users.ts
  verification/curator-service/api/src/index.ts
  verification/curator-service/api/src/model/user.ts
  verification/curator-service/api/test/auth.test.ts
  verification/curator-service/api/test/cases.test.ts
  verification/curator-service/api/test/sources.test.ts
  verification/curator-service/api/test/users.test.ts
  verification/curator-service/api/test/users/base.json
  verification/curator-service/api/tsconfig.json
  verification/curator-service/auth.md
  verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
  verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts
  verification/curator-service/ui/cypress/support/commands.ts
  verification/curator-service/ui/cypress/support/index.ts
Labels: enhancement

#204 Add automation details to the ingestion sources UI
  dev/README.md
  dev/docker-compose.yml
  verification/curator-service/ui/src/components/SourceTable.test.tsx
  verification/curator-service/ui/src/components/SourceTable.tsx
Labels: enhancement
