Repository globaldothealth/list, pull requests merged in 2020-07, with the labels that each got.

#403 Update readme with .env changes
  dev/README.md
Labels: documentation

#395 Check for the presence of sourceEntryId in case upsert API method
  data-serving/data-service/src/controllers/case.ts
  data-serving/data-service/test/controllers/case.test.ts
Labels: bug

#402 Finalize base field format and parsing for bulk upload
  verification/curator-service/ui/cypress/fixtures/bad_bulk_data.csv
  verification/curator-service/ui/cypress/fixtures/bulk_data.csv
  verification/curator-service/ui/cypress/fixtures/updated_bulk_data.csv
  verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
  verification/curator-service/ui/src/components/Case.tsx
  verification/curator-service/ui/src/components/ViewCase.tsx
Labels: enhancement

#414 Use remote autocomplete for the source UI form component
  verification/curator-service/api/openapi/openapi.yaml
  verification/curator-service/api/src/controllers/sources.ts
  verification/curator-service/api/test/sources.test.ts
  verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
  verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
  verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx
  verification/curator-service/ui/src/components/common-form-fields/Source.tsx
Labels: enhancement

#451 Fill source URL when a case is edited.
  verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
  verification/curator-service/ui/src/components/CaseForm.tsx
  verification/curator-service/ui/src/components/EditCase.test.tsx
  verification/curator-service/ui/src/components/common-form-fields/Source.tsx
Labels: enhancement

#460 Update the Source component to operate on CaseReference; add creation dialog
  verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
  verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
  verification/curator-service/ui/cypress/integration/utils/enterSource.ts
  verification/curator-service/ui/src/components/BulkCaseForm.test.tsx
  verification/curator-service/ui/src/components/BulkCaseForm.tsx
  verification/curator-service/ui/src/components/CaseForm.test.tsx
  verification/curator-service/ui/src/components/CaseForm.tsx
  verification/curator-service/ui/src/components/EditCase.test.tsx
  verification/curator-service/ui/src/components/common-form-fields/Source.tsx
  verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx
Labels: enhancement

#472 Add an example of preparing Ohio's state data.
  verification/curator-service/ui/README.md
  verification/curator-service/ui/ohio.gif
Labels: Documentation
